services:
  airflow-webserver:
    image: apache/airflow:2.8.1-python3.11
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
      - ./:/opt/airflow/mlops
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1-python3.11
    restart: always
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
      - ./:/opt/airflow/mlops
    command: scheduler

  airflow-init:
    image: apache/airflow:2.8.1-python3.11
    restart: on-failure
    volumes:
      - ./dags:/opt/airflow/dags
      - airflow_data:/opt/airflow
    entrypoint: >
      /bin/bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com
      "

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    restart: always
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns

volumes:
  airflow_data:
